import Link from "next/link";
import React from "react";
import Head  from 'next/head';

const Custom404 = () => {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" />
        <link rel="shortcut icon" href="/favicon.svg" type="image/x-icon" />
        <title>Error</title>
      </Head>
      <div className="error">
        <h1> Error 404 ! Page is not found!</h1>
        <Link href="/"><a>👉🏻 Home</a></Link>
      </div>
    </>
  );
};

export default Custom404;
