import type { NextPage } from "next";
import Head from "next/head";
import Script from "next/script";
import { Navbar } from "../app/layouts";

const Home: NextPage = () => {
  return (
    <div className="app">
      <Head>
        <title>Cargo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" />
        <link rel="shortcut icon" href="/favicon.svg" type="image/x-icon" />
      </Head>
      <Navbar/>

      <Script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
        crossOrigin="anonymous"
      />
    </div>
  );
};

export default Home;
